"""
Sync the browsable template-library HTML into the skill's catalog.

The browsable library (smartbuild_slide_template_library_vN.html) is the master
that template authors edit/regenerate. This extracts its embedded template data
into the skill's machine-readable catalog + a human-readable index, so template
work flows into the skill in ONE command (no manual re-extract).

Usage:
    python engine/sync_library.py --html "<path to the library .html>" [--out layouts/library-v9]
"""
import argparse, json, os, re, sys

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--html", required=True, help="path to the browsable template library .html")
    ap.add_argument("--out", default=None, help="output dir (default: layouts/library-v9 next to this script)")
    args = ap.parse_args()

    skill = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out = args.out or os.path.join(skill, "layouts", "library-v9")
    if not os.path.exists(args.html):
        print("HTML not found:", args.html); sys.exit(1)

    html = open(args.html, encoding="utf-8").read()
    blocks = re.findall(r'<script[^>]*type="application/json"[^>]*>(.*?)</script>', html, re.S)
    data = None
    for b in blocks:
        try:
            j = json.loads(b)
            if isinstance(j, dict) and "layouts" in j:
                data = j; break
        except Exception:
            pass
    if not data:
        print("No embedded template JSON found in", args.html); sys.exit(2)

    lay = data["layouts"]
    slim = [{k: v for k, v in it.items() if k != "svg"} for it in lay]  # metadata only; builder doesn't need svg
    os.makedirs(out, exist_ok=True)
    json.dump({"summary": data.get("summary"), "layouts": slim},
              open(os.path.join(out, "catalog.json"), "w", encoding="utf-8"), indent=2, ensure_ascii=False)

    fams = {}
    for it in lay:
        fams.setdefault(it.get("family", "Other"), []).append(it)
    with open(os.path.join(out, "INDEX.md"), "w", encoding="utf-8") as f:
        f.write("# SmartBuild Template Library — %d templates\n_(generated by sync_library.py from %s)_\n\n" % (len(lay), os.path.basename(args.html)))
        for fam, items in fams.items():
            f.write("## %s (%d)\n" % (fam, len(items)))
            for it in items:
                f.write("- **%s** %s — %s\n" % (it.get("id", "?"), it.get("title", ""), (it.get("story_job") or "").strip()))
            f.write("\n")

    print("Synced %d templates -> %s (catalog.json + INDEX.md)" % (len(lay), out))

if __name__ == "__main__":
    main()
