#!/bin/bash
# SmartBuild deck live-editor launcher (generated by html-deck-v5; regenerated on every build)
# Starts the local edit server and opens the deck as a PowerPoint-style editor.
cd "/Users/zainmalik/.claude/skills/html-deck-v5/layouts/library-v9/_preview"
exec "/Library/Frameworks/Python.framework/Versions/3.14/bin/python3" "/Users/zainmalik/.claude/skills/html-deck-v5/engine/open_deck.py" --edit --out "/Users/zainmalik/.claude/skills/html-deck-v5/layouts/library-v9/_preview/out" --plan "/Users/zainmalik/.claude/skills/html-deck-v5/layouts/library-v9/_preview/plan.json"
